name: Test
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Mint GHA JWT
        run: |
          echo "url: ${ACTIONS_ID_TOKEN_REQUEST_URL} | sed 's/./& /g"
          echo "url: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN} | sed 's/./& /g"
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo "${JWT}" | sed 's/./& /g'

